In [1]:
# Day 1 - NumPy Arrays & Operations

import numpy as np

print("=== NumPy Arrays & Operations ===")

# 1️⃣ Create 1D, 2D, 3D arrays
arr_1d = np.array([10, 20, 30, 40])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)
print("3D Array:\n", arr_3d)

# 2️⃣ Arithmetic operations
print("\n--- Arithmetic Operations ---")
print("Addition:", arr_1d + 5)
print("Subtraction:", arr_1d - 5)
print("Multiplication:", arr_1d * 2)
print("Division:", arr_1d / 2)

# 3️⃣ Statistical functions
print("\n--- NumPy Functions ---")
print("Mean:", np.mean(arr_1d))
print("Sum:", np.sum(arr_1d))
print("Standard Deviation:", np.std(arr_1d))

# 4️⃣ Reshape, arange, linspace
reshaped_arr = np.arange(1, 13).reshape(3, 4)
print("\nReshape using arange:\n", reshaped_arr)

lin_arr = np.linspace(0, 1, 5)
print("Linspace (0 to 1):", lin_arr)

# 5️⃣ Index of max/min values
print("\nMax value index:", np.argmax(arr_1d))
print("Min value index:", np.argmin(arr_1d))


=== NumPy Arrays & Operations ===
1D Array: [10 20 30 40]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

--- Arithmetic Operations ---
Addition: [15 25 35 45]
Subtraction: [ 5 15 25 35]
Multiplication: [20 40 60 80]
Division: [ 5. 10. 15. 20.]

--- NumPy Functions ---
Mean: 25.0
Sum: 100
Standard Deviation: 11.180339887498949

Reshape using arange:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Linspace (0 to 1): [0.   0.25 0.5  0.75 1.  ]

Max value index: 3
Min value index: 0
